# https://docs.github.com/cn/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Hello World'
description: 'Greet someone and record the time'
author: 'jamesyang <i@xhlr.top>'
branding:
  icon: ''
  color: ''
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  a:
    description: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
